# Generated by Django 4.2.7 on 2025-10-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Élément de portfolio',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Élément de watchlist',
                'verbose_name_plural': 'Watchlist',
                'ordering': ['order', '-added_at'],
                'unique_together': {('user_profile', 'symbol')},
            },
        ),
    ]
