# Generated by Django 4.2.7 on 2025-10-29 13:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_balance', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Solde de trading',
                'verbose_name_plural': 'Soldes de trading',
            },
        ),
    ]
