# Generated by Django 4.2.7 on 2025-10-31 01:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_and_more'),
        ('watchlist', '0002_tradingbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('finance', 'Finance'), ('trading', 'Trading Spot'), ('margin', 'Marge')], default='trading', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Compte de trading',
                'verbose_name_plural': 'Comptes de trading',
                'ordering': ['-created_at'],
                'unique_together': {('user_profile', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to='watchlist.tradingaccount')),
            ],
            options={
                'verbose_name': 'Historique du wallet',
                'verbose_name_plural': 'Historiques des wallets',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', '-timestamp'], name='watchlist_w_account_824cfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Marché'), ('limit', 'Limite'), ('stop', 'Stop Loss'), ('stop_limit', 'Stop Limit')], default='market', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0.001'), max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_loss_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='watchlist.tradingaccount')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_trades', to='watchlist.trade')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['account', '-executed_at'], name='watchlist_t_account_894ae8_idx'), models.Index(fields=['symbol', '-executed_at'], name='watchlist_t_symbol_4455e6_idx')],
            },
        ),
    ]
