# Generated by Django 4.2.7 on 2025-10-31 02:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_tradingaccount_wallethistory_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='borrowed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='max_leverage',
            field=models.IntegerField(default=5),
        ),
    ]
