# Generated by Django 4.2.7 on 2025-10-31 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_tradingaccount_borrowed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_positions', to='watchlist.tradingaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('account', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['account', 'symbol'], name='watchlist_p_account_299145_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user_profile', 'symbol'], name='watchlist_p_user_pr_05b81e_idx'),
        ),
    ]
