# Generated by Django 4.2.7 on 2025-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
